Track "origin" asset name in job status for accurate reporting and filtering
praetorian-inc/chariot-client pull request #77
Opened 2024-09-18 18:06 UTC by praetorian-harry

Addresses: https://github.com/praetorian-inc/chariot-ui/issues/699

By tracking the "origin" asset name directly on the job status, we can easily identify relevant jobs for a particular integration. This is important when there are multiple integrations of the same type (e.g. multiple AWS organizations) and when capabilities divide their scanning into smaller sub-sections of the integrated entity (e.g. AWS organizations splitting into constituent accounts).

**Note:**  there is a linked PR with additional necessary backend changes. (pending)

2024-09-18 19:16 UTC, noah-tutt-praetorian commented on pkg/sdk/model/job.go
> +		Status:  fmt.Sprintf("%s#%s#%s", Queued, source, origin),
overall I think this makes sense, but I am a little hung up on expanding this key again so soon. it makes me wonder if this is the right approach or if there's something more generic we can do

2024-09-19 05:32 UTC, peter-kwan commented on pkg/sdk/model/job.go
> +		Status:  fmt.Sprintf("%s#%s#%s", Queued, source, origin),
I am a little less concerned about extending the status field because this is Job. The records exist only for 24 hours so if this happened to be a bad choice, we won't need to go through migration to have it clear out of the system.

I would be similarly concerned if we are doing this with Risk or Asset.

This approach will in fact let us kill two birds in one stone: it allows for performant counts on the Overview page, as well as filtering on the Jobs page.

2024-09-19 12:11 UTC, noah-tutt-praetorian commented on pkg/sdk/model/job.go
> +		Status:  fmt.Sprintf("%s#%s#%s", Queued, source, origin),
That's a reasonable argument, I think I'm alright with this then

2024-09-19 15:04 UTC, noah-tutt-praetorian approved these changes

2024-09-19 16:48 UTC, privateducky commented on pkg/sdk/model/job.go
> +		Status:  fmt.Sprintf("%s#%s#%s", Queued, source, origin),
I see both sides; but I'd fall on peter's side of the argument too

2024-09-19 16:50 UTC, privateducky commented on pkg/sdk/model/job.go
> +func NewJob(source string, asset Asset, origin string) Job {
taking this extra parameter feels like a hack; most of the time it should be the asset, which is already passed in as a parameter.. I also don't love passing the parameter in, only to extend a key (which is a hack on its own accord).

2024-09-19 16:50 UTC, privateducky requested changes
this is a shaky approach to me

2024-09-19 16:59 UTC, praetorian-harry commented on pkg/sdk/model/job.go
> +func NewJob(source string, asset Asset, origin string) Job {
@privateducky given the "spidering" of our job pipeline, the `origin` string is often not taken from the `asset` argument that is already passed in. What we're tracking with the `origin` string is the `Name` field of the "originating" asset, e.g. AWS account ID, GCP project, Azure subscription

We're doing this so that every job can be tracked back to the specific integration they originate from, especially in cases where there are multiple integration instances of the same type, e.g. multiple AWS orgs

2024-09-19 18:05 UTC, privateducky commented on pkg/sdk/model/job.go
> +func NewJob(source string, asset Asset, origin string) Job {
oh, I get it :) we're basically using this approach instead of "source"... so one option could be adjusting how we approach job.source

2024-09-19 21:32 UTC, praetorian-harry commented on pkg/sdk/model/job.go
> +func NewJob(source string, asset Asset, origin string) Job {
makes sense! I'm going to test out an approach that modifies `job.Source` instead :+1:

2024-09-19 21:32 UTC, praetorian-harry commented
closing this PR, I'm going to work on an approach that modifies `job.Source` instead

2024-09-19 21:32 UTC, closed without merging